### ISSUE TITLE
Debian 10 instructions for Java create broken installation

### ISSUE THREAD

**Issue by bhartshorn** [jitsi/handbook#141]
The[ installation manual quickstart](https://github.com/jitsi/handbook/blob/master/docs/devops-guide/quickstart.md) encourages users to install a 3rd-party java8 package. Myself and at least [one other user](https://community.jitsi.org/t/solved-no-video-whith-jitsi-meet-now-when-the-third-participant-connects/91507/2) spent hours troubleshooting broken 3-way video, to find that it works with the `openjdk-11` package in default Debian repos.

Is Java 11 officially supported? Can the instructions be updated to encourage using the Java 11 package for each distro?

**Comment by saghul** [comment]
That's odd. Our Docker setup uses that very same JDK version (AdoptOpenJDK 8) with no such issues. More importantly, the reason why we recommend is because that's what we deploy in production and are most comfortable with. Java 11 *may* work just fine, but we don't develop, test or deploy our software with it.

**Comment by SamuelNitsche** [comment]
I can confirm what @bhartshorn said.
See https://community.jitsi.org/t/users-cant-see-hear-each-other-nothing-listens-on-port-10000/86919

**Comment by saghul** [comment]
The instructions have since been updated.

**Comment by bhartshorn** [comment]
@saghul Thank you! Great work on a great project, keep it up!
