### ISSUE TITLE
Remove localhost-Line from DevOps Guide

### ISSUE THREAD

**Issue by datenritter** [jitsi/handbook#9]
The DevOps-Guide asks you to add
`127.0.0.1 localhost meet.example.org`
to your /etc/hosts file.

From my experience, this is not required. (If you think, it is required so the videobridge can find the TURN-server, I'd recommend to use the public IP for that.)

**Comment by saghul** [comment]
Transfered it here to where it belongs.

Care to open a PR with improvements?

**Comment by toby63** [comment]
@saghul Can you explain why this was closed?
I still see this: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart#set-up-the-fully-qualified-domain-name-fqdn-optional

I think this is a bit missleading, because a server will not solely be used for jitsi-meet, so in general one will link the domain to the ip of the server, instead of setting the server's hostname.
